"""initial schema

Revision ID: 1c1dccd138fb
Revises:
Create Date: 2026-08-03 20:53:44.107412
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.models import UTCDateTime

revision = '1c1dccd138fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('author_feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('manual_command_id', sa.String(length=36), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canon_decision_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_type', sa.String(length=32), nullable=False),
    sa.Column('local_key', sa.String(length=120), nullable=True),
    sa.Column('candidate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_revision_id', sa.String(length=36), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_snapshots_chapter_id'), 'chapter_snapshots', ['chapter_id'], unique=False)
    op.create_table('command_idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_scope', sa.String(length=120), nullable=False),
    sa.Column('operation_name', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('claim_lease', sa.String(length=120), nullable=True),
    sa.Column('claim_expires_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('first_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_ref', sa.String(length=120), nullable=True),
    sa.Column('manual_command_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_scope', 'operation_name', 'idempotency_key', name='uq_idempotency_key')
    )
    op.create_table('context_manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('source_index', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_run_id', name='uq_context_manifest_run')
    )
    op.create_index(op.f('ix_context_manifests_generation_run_id'), 'context_manifests', ['generation_run_id'], unique=False)
    op.create_table('fact_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_identity', sa.String(length=120), nullable=False),
    sa.Column('candidate_type', sa.String(length=32), nullable=False),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=True),
    sa.Column('source_draft_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source_change_set_id', sa.String(length=36), nullable=True),
    sa.Column('source_identity', sa.String(length=120), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('local_key', sa.String(length=120), nullable=True),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(source_revision_id IS NOT NULL)::int + (source_draft_artifact_id IS NOT NULL)::int + (source_change_set_id IS NOT NULL)::int = 1', name='ck_candidate_source_exactly_one'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_id', 'scene_id', 'scope', 'source_identity', 'candidate_type', 'candidate_fingerprint', name='uq_candidate_source_fingerprint')
    )
    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('parent_generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('supersedes_run_id', sa.String(length=36), nullable=True),
    sa.Column('parent_plan_revision_id', sa.String(length=36), nullable=True),
    sa.Column('plan_revision_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('run_version', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('write_owner_kind', sa.String(length=32), nullable=True),
    sa.Column('write_owner_id', sa.String(length=120), nullable=True),
    sa.Column('write_fencing_token', sa.Integer(), nullable=False),
    sa.Column('last_durable_node', sa.String(length=120), nullable=True),
    sa.Column('trace_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_project_id'), 'generation_runs', ['project_id'], unique=False)
    op.create_table('novel_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=120), nullable=False),
    sa.Column('target_reader', sa.String(length=255), nullable=False),
    sa.Column('default_style', sa.String(length=255), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_thread_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_identity', sa.String(length=120), nullable=False),
    sa.Column('candidate_type', sa.String(length=32), nullable=False),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=True),
    sa.Column('source_draft_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source_change_set_id', sa.String(length=36), nullable=True),
    sa.Column('source_identity', sa.String(length=120), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('local_key', sa.String(length=120), nullable=True),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(source_revision_id IS NOT NULL)::int + (source_draft_artifact_id IS NOT NULL)::int + (source_change_set_id IS NOT NULL)::int = 1', name='ck_plot_thread_source_exactly_one'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_id', 'scene_id', 'scope', 'source_identity', 'candidate_type', 'candidate_fingerprint', name='uq_plot_thread_source_fingerprint')
    )
    op.create_table('run_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('request_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_run_id', 'target', 'idempotency_key', name='uq_run_decision')
    )
    op.create_index(op.f('ix_run_decisions_generation_run_id'), 'run_decisions', ['generation_run_id'], unique=False)
    op.create_table('run_event_consumer_cursors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consumer_name', sa.String(length=120), nullable=False),
    sa.Column('stream_key', sa.String(length=120), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_name', 'stream_key', name='uq_consumer_cursor')
    )
    op.create_table('run_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('generation_run_id', 'sequence', name='uq_run_event_sequence')
    )
    op.create_index(op.f('ix_run_events_generation_run_id'), 'run_events', ['generation_run_id'], unique=False)
    op.create_table('run_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=False),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=120), nullable=False),
    sa.Column('lease_expires_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_leases_generation_run_id'), 'run_leases', ['generation_run_id'], unique=False)
    op.create_table('run_outbox_records',
    sa.Column('outbox_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('payload_schema', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('producer_command_id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'producer_command_id', name='uq_outbox_resource')
    )
    op.create_table('scene_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('scene_revision_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_snapshots_scene_id'), 'scene_snapshots', ['scene_id'], unique=False)
    op.create_table('timeline_event_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_identity', sa.String(length=120), nullable=False),
    sa.Column('candidate_type', sa.String(length=32), nullable=False),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=True),
    sa.Column('source_draft_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source_change_set_id', sa.String(length=36), nullable=True),
    sa.Column('source_identity', sa.String(length=120), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('local_key', sa.String(length=120), nullable=True),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(source_revision_id IS NOT NULL)::int + (source_draft_artifact_id IS NOT NULL)::int + (source_change_set_id IS NOT NULL)::int = 1', name='ck_timeline_source_exactly_one'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_id', 'scene_id', 'scope', 'source_identity', 'candidate_type', 'candidate_fingerprint', name='uq_timeline_source_fingerprint')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_generation_run_id'), 'agent_runs', ['generation_run_id'], unique=False)
    op.create_table('canon_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canon_facts_project_id'), 'canon_facts', ['project_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'kind', name='uq_entity')
    )
    op.create_index(op.f('ix_entities_project_id'), 'entities', ['project_id'], unique=False)
    op.create_table('foreshadowings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadowings_project_id'), 'foreshadowings', ['project_id'], unique=False)
    op.create_table('volumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('mainline', sa.Text(), nullable=False),
    sa.Column('time_range', sa.String(length=255), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volumes_project_id'), 'volumes', ['project_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('volume_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pov', sa.String(length=120), nullable=False),
    sa.Column('chapter_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chapter_sync_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_volume_id'), 'chapters', ['volume_id'], unique=False)
    op.create_table('chapter_handoffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('source_chapter_revision_id', sa.String(length=36), nullable=False),
    sa.Column('entry_handoff_status', sa.String(length=32), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_handoffs_chapter_id'), 'chapter_handoffs', ['chapter_id'], unique=False)
    op.create_table('chapter_plan_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('parent_plan_revision_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_plan_revisions_chapter_id'), 'chapter_plan_revisions', ['chapter_id'], unique=False)
    op.create_table('chapter_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('parent_revision_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_revisions_chapter_id'), 'chapter_revisions', ['chapter_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scene_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_chapter_id'), 'scenes', ['chapter_id'], unique=False)
    op.create_table('chapter_plan_revision_links',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('plan_revision_id', sa.String(length=36), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_revision_id'], ['chapter_plan_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    op.create_table('chapter_revision_scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_revision_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('scene_revision_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_revision_id'], ['chapter_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_revision_id', 'scene_id', name='uq_chapter_rev_scene')
    )
    op.create_index(op.f('ix_chapter_revision_scenes_chapter_revision_id'), 'chapter_revision_scenes', ['chapter_revision_id'], unique=False)
    op.create_table('scene_draft_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('manual_command_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scene_draft_artifact_run_agent', 'scene_draft_artifacts', ['generation_run_id', 'agent_run_id', 'idempotency_key'], unique=False)
    op.create_index(op.f('ix_scene_draft_artifacts_scene_id'), 'scene_draft_artifacts', ['scene_id'], unique=False)
    op.create_table('scene_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('parent_revision_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_revisions_scene_id'), 'scene_revisions', ['scene_id'], unique=False)
    op.create_index('ix_scene_revisions_scene_parent', 'scene_revisions', ['scene_id', 'parent_revision_id'], unique=False)
    op.create_table('change_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('base_scene_revision_id', sa.String(length=36), nullable=True),
    sa.Column('operation_format', sa.String(length=32), nullable=False),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('root_draft_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['root_draft_artifact_id'], ['scene_draft_artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_draft_artifact_id')
    )
    op.create_index(op.f('ix_change_sets_scene_id'), 'change_sets', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_sets_scene_id'), table_name='change_sets')
    op.drop_table('change_sets')
    op.drop_index('ix_scene_revisions_scene_parent', table_name='scene_revisions')
    op.drop_index(op.f('ix_scene_revisions_scene_id'), table_name='scene_revisions')
    op.drop_table('scene_revisions')
    op.drop_index(op.f('ix_scene_draft_artifacts_scene_id'), table_name='scene_draft_artifacts')
    op.drop_index('ix_scene_draft_artifact_run_agent', table_name='scene_draft_artifacts')
    op.drop_table('scene_draft_artifacts')
    op.drop_index(op.f('ix_chapter_revision_scenes_chapter_revision_id'), table_name='chapter_revision_scenes')
    op.drop_table('chapter_revision_scenes')
    op.drop_table('chapter_plan_revision_links')
    op.drop_index(op.f('ix_scenes_chapter_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_chapter_revisions_chapter_id'), table_name='chapter_revisions')
    op.drop_table('chapter_revisions')
    op.drop_index(op.f('ix_chapter_plan_revisions_chapter_id'), table_name='chapter_plan_revisions')
    op.drop_table('chapter_plan_revisions')
    op.drop_index(op.f('ix_chapter_handoffs_chapter_id'), table_name='chapter_handoffs')
    op.drop_table('chapter_handoffs')
    op.drop_index(op.f('ix_chapters_volume_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_volumes_project_id'), table_name='volumes')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_foreshadowings_project_id'), table_name='foreshadowings')
    op.drop_table('foreshadowings')
    op.drop_index(op.f('ix_entities_project_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_canon_facts_project_id'), table_name='canon_facts')
    op.drop_table('canon_facts')
    op.drop_index(op.f('ix_agent_runs_generation_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('timeline_event_candidates')
    op.drop_index(op.f('ix_scene_snapshots_scene_id'), table_name='scene_snapshots')
    op.drop_table('scene_snapshots')
    op.drop_table('run_outbox_records')
    op.drop_index(op.f('ix_run_leases_generation_run_id'), table_name='run_leases')
    op.drop_table('run_leases')
    op.drop_index(op.f('ix_run_events_generation_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_table('run_event_consumer_cursors')
    op.drop_index(op.f('ix_run_decisions_generation_run_id'), table_name='run_decisions')
    op.drop_table('run_decisions')
    op.drop_table('plot_thread_updates')
    op.drop_table('novel_projects')
    op.drop_index(op.f('ix_generation_runs_project_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_table('fact_candidates')
    op.drop_index(op.f('ix_context_manifests_generation_run_id'), table_name='context_manifests')
    op.drop_table('context_manifests')
    op.drop_table('command_idempotency_records')
    op.drop_index(op.f('ix_chapter_snapshots_chapter_id'), table_name='chapter_snapshots')
    op.drop_table('chapter_snapshots')
    op.drop_table('canon_decision_records')
    op.drop_table('author_feedbacks')
    # ### end Alembic commands ###
